---
n_experiments: 1 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    name: &env_name BipedalWalker-v2
    max_episode_steps: 1000
agent:
    gamma: &gamma 0.99
    tau: 0.001      # moving average rate
    batch_size: &batch_size 128
    done: 1
    num_workers: 10

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: tensorboard_root_dir/model_dir/model_name
    model_root_dir: ./saved_models            # root path for savinng models
    tensorboard_root_dir: ./tensorboard_logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: 0311-workers10-add_IS_to_actor-alpha4

    # options for different improvements on DDPG
    options:
        # noisy layer is used as the default strategy to introduce exploration
        n_steps: &n_steps 3
    
    actor:
        optimizer:
            learning_rate: 1e-4
        noisy_sigma: 0.4    # standard deviation for noisy layers
    critic:
        optimizer:
            learning_rate: 3e-4
        loss_type: mse   # huber or mse
        extra_updates: 0

# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional
    batch_size: *batch_size
    n_steps: *n_steps
    gamma: *gamma

    alpha: 0.4
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e6
    min_size: 1e4
    capacity: 1e6
