---
n_experiments: 1 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    name: &env_name BipedalWalker-v2
    max_episode_steps: 1000
agent:
    gamma: &gamma 0.99
    tau: 0.001      # moving average rate
    batch_size: &batch_size 128
    done: 1

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: tensorboard_root_dir/model_dir/model_name
    model_root_dir: ./saved_models            # root path for savinng models
    tensorboard_root_dir: ./tensorboard_logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: 0228-optimization

    # options for different improvements on DDPG
    options:
        # noisy layer is used as the default strategy to introduce exploration
        buffer_type: &buffer_type proportional  # rank, proportional
        double_Q: True           # double is implemented based on TD3
        distributional: False
        n_steps: &n_steps 3
        
    actor:
        optimizer:
            learning_rate: 0.0001
        noisy_sigma: 0.4    # standard deviation for noisy layers
    critic:
        optimizer:
            learning_rate: 0.0003
        loss_type: mse   # huber or mse
        update_times: 1

# argumennts for prioritized replay
buffer:
    type: *buffer_type 
    batch_size: *batch_size
    n_steps: *n_steps
    gamma: *gamma

    alpha: 0.1
    beta0: 0.4
    epsilon: 0.0001
    beta_steps: 500000
    min_size: 1000
    capacity: 1000000
    categories: 5
    min_elements: 1          # minimum number of elements in a rank
    top_priority: 2.
