---
n_experiments: 0 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    atari: True
    video_path: video
    name: &env_name PongNoFrameskip-v4    # LunarLanderContinuous-v2
    seed: 0
agent:
    background_learning: False
    gamma: &gamma 0.99
    algorithm: rainbow
    batch_size: &batch_size 32
    prefetches: 5

    # model path: model_root_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs  # root path for tensorboard logs
    model_name: baseline

    frame_history_len: 4
    n_steps: 3
    loss_type: mse   # huber or mse
    
    networks:
        polyak: .995
        distributional: False
        duel: True
        noisy_sigma: 0.5    # standard deviation for noisy layers
        n_atoms: 51
        v_min: -10
        v_max: 10
        # args for optimizer
        learning_rate: 6.25e-5
        epsilon: 1.5e-4

    env_stats:
        times: 1
        stats: [score, avg_score, eps_len, avg_eps_len]

# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional

    alpha: 0.4
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e5
    min_size: 8e4
    capacity: 1e6
