---
env:
    name: &env_name BipedalWalker-v2    # LunarLanderContinuous-v2
    max_episode_steps: 1000
agent:
    algorithm: td3
    gamma: &gamma 0.99
    tau: 0.005      # moving average rate
    batch_size: &batch_size 128
    n_workers: 10
    prefetches: 3

    # model path: model_root_dir/model_dir/model_name
    # tensorboard path: log_root_dir/model_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: baseline

    n_steps: &n_steps 3
    policy_delay: 1     # policy will be updated once every policy_delay steps

    actor:
        n_fc: 1
        units: [500, 300]
        noisy_sigma: 0.4    # standard deviation for noisy layers
        # args for optimizer
        learning_rate: 1e-4
        
    critic:
        units: [500, 500, 300]
        loss_type: mse   # huber or mse
        # args for optimizer
        learning_rate: 3e-4

# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional
    batch_size: *batch_size
    n_steps: *n_steps
    gamma: *gamma

    alpha: 0.4
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 5e5
    min_size: 1e3
    capacity: 1e6
