---
env:
    name: &env_name BipedalWalker-v2    # LunarLanderContinuous-v2
    video_path: video
    log_video: False
    max_episode_steps: 1000
    seed: 0
    clip_reward: none
agent:
    algorithm: td3
    gamma: 0.99
    polyak: 0.995                           # moving average rate
    batch_size: 256
    episodic_learning: False                 # whether to update network after each episode. Update after each step if False
    max_action_repetitions: 1

    # model path: model_root_dir/model_name
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs                      # root path for tensorboard logs
    model_name: baseline

    n_steps: 3
    n_epochs: 400
    
    actor:
        n_noisy: 2                          # number of noisy layer
        units: [512, 256, 128]
        noisy_sigma: 0.4                    # standard deviation for noisy layers
        norm: layer
        # args for optimizer
        learning_rate: 1e-4
        decay_rate: &decay_rate .95
        decay_steps: &decay_steps 1e4
    critic:
        units: [512, 512, 256]
        loss_type: mse                      # huber or mse
        norm: layer
        # args for optimizer
        learning_rate: 3e-4
        decay_rate: *decay_rate
        decay_steps: *decay_steps

    env_stats:
        times: 1
        stats: [score, score_mean, score_std, epslen_mean, epslen_std]

# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional
    normalize_reward: False
    reward_scale: 1
    to_update_priority: True

    alpha: 0.4
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 5e4     # number of sampling steps taken beta to reach 1
    min_size: 5e3
    capacity: 1e6

    tb_capacity: 100
