---
n_experiments: 0 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    name: &env_name BipedalWalker-v2    # LunarLanderContinuous-v2
    max_episode_steps: 1000
agent:
    gamma: &gamma 0.99
    tau: 0.005      # moving average rate
    batch_size: &batch_size 32
    num_workers: 1

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: tensorboard_root_dir/model_dir/model_name
    model_root_dir: ./data/saved_models            # root path for savinng models
    tensorboard_root_dir: ./data/tensorboard_logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: 0314-500_500_500-buffer2-sigma6

    Q:
        n_steps: &n_steps 3
        distributional: False
        duel: True
        loss_type: mse   # huber or mse
        units: [500, 500, 300]
        noisy_sigma: 0.5    # standard deviation for noisy layers
        n_atoms: 51
        v_min: -10
        v_max: 10
        optimizer:
            learning_rate: 6.25e-5
            epsilon: 1.5e-4


# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional
    batch_size: *batch_size
    n_steps: *n_steps
    gamma: *gamma

    alpha: 0.5
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 5e5
    min_size: 8e4
    capacity: 1e6
