---
env:
    name: &env_name BipedalWalker-v2
    video_path: video
    log_video: False
    max_episode_steps: 1000
    seed: 0
    clip_reward: none
agent:
    algorithm: sac
    temperature: auto                       # auto or some float, e.g., 0.01
    gamma: &gamma 0.99
    batch_size: 256
    episodic_learning: False                # whether to update network after each episode. Update after each step if False
    max_action_repetition: 3

    # model path: model_root_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs                      # root path for tensorboard logs
    model_name: baseline

    loss_type: mse                          # huber or mse
    n_steps: 3           
    n_epochs: 400
    
    Policy:
        n_noisy: 2
        noisy_sigma: 0.4                    # standard deviation for noisy layers
        units: [512, 256, 128]
        layernorm: True
        target: False
        # args for optimizer
        learning_rate: &policy_lr 1e-4
        decay_rate: &decay_rate .95
        decay_steps: &decay_steps 1e4
    Q:
        polyak: .995                        # moving average rate
        units: [512, 512, 256]
        layernorm: True
        # args for optimizer
        learning_rate: 3e-4
        decay_rate: *decay_rate
        decay_steps: *decay_steps
    Temperature:
        type: state_action
        noisy: False
        # args for optimizer
        learning_rate: *policy_lr
        decay_rate: *decay_rate
        decay_steps: *decay_steps

    env_stats:
        times: 1
        stats: [score, score_mean, score_std, epslen_mean, epslen_std]

# argumennts for prioritized replay
buffer:
    type: proportional # proportional
    normalize_reward: False
    reward_scale: 1
    to_update_priority: True

    alpha: 0.4
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 5e4
    min_size: 5e3
    capacity: 1e6

    tb_capacity: 100
