---
env:
    name: &env_name LunarLanderContinuous-v2
    max_episode_steps: 1000
    seed: 0
agent:
    algorithm: sac
    temperature: 0.2
    gamma: &gamma 0.99
    batch_size: &batch_size 128
    n_workers: &n_workers 10
    prefetches: 5

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: log_root_dir/model_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: baseline

    loss_type: mse            # huber or mse
    n_steps: &n_steps 3
    priority: Q               # Q or V
    policy_delay: 1
    n_epochs: 5000
    
    policy:
        noisy_sigma: 0.4    # standard deviation for noisy layers
        units: [64, 64]
        # args for optimizer
        learning_rate: 1e-4
        layernorm: True
    V:
        polyak: .995      # moving average rate
        units: &critic_units [64, 64]
        # args for optimizer
        learning_rate: &critic_lr 1e-4
        layernorm: True
    Q:
        units: *critic_units
        # args for optimizer
        learning_rate: *critic_lr
        layernorm: True

    env_stats:
        times: *n_workers
        stats: [score, avg_score, eps_len, avg_eps_len]

# argumennts for prioritized replay
buffer:
    type: proportional # proportional
    batch_size: *batch_size
    n_steps: *n_steps
    gamma: *gamma

    alpha: 0.4
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e5
    min_size: 1e3
    capacity: 1e6
