---
n_experiments: 1 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    name: &env_name LunarLanderContinuous-v2
    max_episode_steps: 1000
agent:
    temperature: 0.01
    gamma: &gamma 0.99
    batch_size: &batch_size 128
    n_workers: 10

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: log_root_dir/model_dir/model_name
    model_root_dir: ./data/saved_models            # root path for savinng models
    log_root_dir: ./data/logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: 0315-baseline

    loss_type: mse            # huber or mse
    n_steps: &n_steps 3
    extra_critic_updates: 0
    priority: Q               # Q or V
    reparameterize: True
    units: &units [500, 500, 300]
    policy_delay: 2
    
    policy:
        noisy_sigma: 0.4    # standard deviation for noisy layers
        units: *units
        # args for optimizer
        learning_rate: 1e-4
    V:
        tau: 0.005      # moving average rate
        units: *units
        # args for optimizer
        learning_rate: 3e-4
    Q:
        units: *units
        # args for optimizer
        learning_rate: 3e-4

# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional
    batch_size: *batch_size
    n_steps: *n_steps
    gamma: *gamma

    alpha: 0.1
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e6
    min_size: 1e4
    capacity: 1e6
