---
n_experiments: 1 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    name: &env_name LunarLanderContinuous-v2
    max_episode_steps: 1000
agent:
    gamma: &gamma 0.99
    batch_size: &batch_size 128
    done: 1
    num_workers: 10

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: tensorboard_root_dir/model_dir/model_name
    model_root_dir: ./data/saved_models            # root path for savinng models
    tensorboard_root_dir: ./data/tensorboard_logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: 0314-baseline

    # options for different improvements on DDPG
    options:
        # noisy layer is used as the default strategy to introduce exploration
        loss_type: mse            # huber or mse
        n_steps: &n_steps 3
        extra_critic_updates: 0
        priority: Q               # Q or V
    
    policy:
        optimizer:
            learning_rate: 1e-4
        noisy_sigma: 0.4    # standard deviation for noisy layers
    V:
        optimizer:
            learning_rate: 3e-4
        tau: 0.005      # moving average rate
    Q:
        optimizer:
            learning_rate: 3e-4

# argumennts for prioritized replay
buffer:
    type: proportional # local or proportional
    batch_size: *batch_size
    n_steps: *n_steps
    gamma: *gamma

    alpha: 0.1
    beta0: 0.4
    epsilon: 1e-4
    beta_steps: 1e5
    min_size: 1e4
    capacity: 1e6
