---
n_experiments: 1 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    name: &env_name LunarLanderContinuous-v2
    max_episode_steps: 1000
ppo:
    n_workers: 8

    gamma: 0.99
    lambda: 0.95
    batch_size: 40000
    n_updates_per_iteration: 1

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: tensorboard_root_dir/model_dir/model_name
    model_root_dir: ./saved_models            # root path for savinng models
    tensorboard_root_dir: ./tensorboard_logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: baseline
        
    actor:
        learning_rate: 0.005
        epsilon: 0.2        # clip range
        entropy_coef: 0.0
        noisy_sigma: 0.4    # standard deviation for noisy layers
    critic:
        learning_rate: 0.005
        loss_type: 'mse'   # huber or mse

