---
n_experiments: 1 # 1 run the following configuration, otherwise, run test code in parallel see train.py
env:
    name: &env_name LunarLanderContinuous-v2 # CartPole-v0, LunarLanderContinuous-v2
    max_episode_steps: 1000
agent:
    n_workers: 16

    gamma: 0.99
    lambda: 0.97
    minibatch_size: 40000
    n_minibatches: 1
    n_epochs: 500

    option:
        advantage_type: norm    # norm or gae
        shuffle: True          # shuffle data or not

    # model path: model_root_dir/model_dir/model_name/model_name, two model_names ensure each model saved in an independent folder
    # tensorboard path: tensorboard_root_dir/model_dir/model_name
    model_root_dir: ./saved_models            # root path for savinng models
    tensorboard_root_dir: ./tensorboard_logs  # root path for tensorboard logs
    model_dir: *env_name
    model_name: norm-random

    optimizer:
        learning_rate: 1e-3
        epsilon: 1e-5

    actor:
        clip_range: 0.2        # clip range for ppo
        entropy_coef: 0.0
        noisy_sigma: 0.4    # standard deviation for noisy layers
        optimizer:
            learning_rate: 1e-4
            epsilon: &eps 1e-5
    critic:
        loss_type: 'mse'   # huber or mse
        optimizer:
            learning_rate: 1e-3
            epsilon: *eps

